# image: docker:latest

# services:
#   - docker:dind

# variables:
#   DOCKER_TLS_CERTDIR: ""  # Disable TLS for DinD

# stages:
#   - build
#   - deploy

# before_script:
#   - echo "Using GitLab CI/CD for staging branch"
#   - apk add --no-cache bash git
#   - mkdir -p backend  # ensure folder exists
#   - echo "$BACKEND_ENV" | tee backend/.env > /dev/null  # create .env file safely

# build:
#   stage: build
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "staging"'
#   script:
#     - docker compose -f docker-compose.yml build

# deploy:
#   stage: deploy
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "staging"'
#   script:
#     - docker compose -f docker-compose.yml up -d


image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""  # Disable TLS for DinD

stages:
  - deploy

before_script:
  - echo "Using GitLab CI/CD for staging branch"
  - apk add --no-cache bash git
  - mkdir -p backend
  - echo "$BACKEND_ENV" | tee backend/.env > /dev/null

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
  script:
    - docker --version
    - docker compose -f docker-compose.yml --compatibility --ansi never up -d
